data:
  class_path: data_loaders.clarity_dataloader.ClarityDataModule
  init_args:
    train_json_file: /teamspace/uploads/clarity_CEC3_data/task2/clarity_data/metadata/scenes.train.json
    test_json_file: /teamspace/uploads/clarity_CEC3_data/task2/clarity_data/metadata/scenes.dev.json
    train_data_path: /teamspace/uploads/clarity_CEC3_data/task2/clarity_data/train/scenes
    test_data_path: /teamspace/uploads/clarity_CEC3_data/task2/clarity_data/train/scenes
    datasets: ["train_cec3_task2", "dev_cec3_task3", "eval_cec3_task2"]
    batch_size: [4, 8]
    train_limit: 1
    val_limit: 1  # Limit validation set to 100 samples, None for full data
    test_limit: 1  # Limit test set to 50 samples, None for full data
    num_workers: 7
